### ISSUE TITLE
Phase Connexion avec intégration et push sur github

### ISSUE THREAD

**Issue by GhassenAskri** [GhassenAskri/Beego#2]
Deadline : Mercredi 06 2018 
Nb  Adem essaye de ne pas compliquer les choses  !! Noublier pas de faire un style pour les alert

**Comment by GhassenAskri** [comment]
![image](https://user-images.githubusercontent.com/19927564/41663321-70269b26-74a3-11e8-8320-255a179dbf8b.png)
le message d erreur doit être en français et il doit être précis car il affiche toujours invalide nom  peut importe l erreur

**Comment by ademoutlaw** [comment]
is done
