### ISSUE TITLE
Menu profile Page 

### ISSUE THREAD

**Issue by GhassenAskri** [GhassenAskri/Beego#22]
![image](https://user-images.githubusercontent.com/19927564/41857245-55cdf740-7897-11e8-9f1d-79f0cd7297dc.png)

**Comment by amirping** [comment]
menu basic sliding created , 
todo : improve sliding way , create the menu content

**Comment by amirping** [comment]
last merge #49    : 

- done menu creation 
- done animation 
- done hiding the tabs 

- [ ] add bottom white svg

**Comment by amirping** [comment]
@GhassenAskri  need the bottom shape in svg to close the issue
