### ISSUE TITLE
implémentation des fonctionalites Acceuil :

### ISSUE THREAD

**Issue by GhassenAskri** [GhassenAskri/Beego#3]
Consultation des espaces (Liste)……………………………………………
Préparation des interfaces et intégration  
implémentation technique  et test              
Consultation des suggestions……………………………………………
Préparation des interfaces et intégration  
implémentation technique  et test             
Consultation des événements……………………………………………
Préparation des interfaces et intégration
implémentation technique  et test        
Consultation des promotions …………………………………………………..
Préparation des interfaces et intégration  
implémentation technique  et test
Dead line  : jeudi 06 2018

**Comment by amirping** [comment]
need rework after changing all the interface logic
