### ISSUE TITLE
Mes gouts integration

### ISSUE THREAD

**Issue by GhassenAskri** [GhassenAskri/Beego#50]
![Uploading image.png…]()
You can manage with amir to make the swap tinder style and the spectial for you Page as providers !!

**Comment by GhassenAskri** [comment]
![image](https://user-images.githubusercontent.com/19927564/42376810-cd98a93c-8120-11e8-9408-95af8c8401ef.png)

**Comment by amirping** [comment]
Vertical Gesture not working (need HammerJs config file)
