### ISSUE TITLE
Map integration 

### ISSUE THREAD

**Issue by GhassenAskri** [GhassenAskri/Beego#66]
![image](https://user-images.githubusercontent.com/19927564/42880118-716e121a-8a93-11e8-9ba1-3f863aed49ef.png)
![image](https://user-images.githubusercontent.com/19927564/42880132-81188970-8a93-11e8-951d-58ea0411a347.png)
![image](https://user-images.githubusercontent.com/19927564/42880139-8a05d934-8a93-11e8-9f1f-86379149c56c.png)
![image](https://user-images.githubusercontent.com/19927564/42880155-9bdbec70-8a93-11e8-8262-69755d40a4c9.png)
![image](https://user-images.githubusercontent.com/19927564/42880172-a9b430d2-8a93-11e8-851b-f3c7f50e31dd.png)
![image](https://user-images.githubusercontent.com/19927564/42880183-b71c3e5e-8a93-11e8-8f53-88f357421155.png)
![image](https://user-images.githubusercontent.com/19927564/42880193-c5dc4650-8a93-11e8-84a4-ed66fb7fd07c.png)
![image](https://user-images.githubusercontent.com/19927564/42880207-d1f5e96e-8a93-11e8-88db-a42d4bb45b3c.png)
![image](https://user-images.githubusercontent.com/19927564/42880221-ddadae9a-8a93-11e8-8c8a-269ed0846ff9.png)

**Comment by amirping** [comment]
- [x] GPS tracking 
- [x] Distance calc
- [x] Path to target draw
- [x] Show location
- [ ] Show Friends
- [ ] Show Events
- [ ] Create Programs
