### ISSUE TITLE
Space Events 

### ISSUE THREAD

**Issue by GhassenAskri** [GhassenAskri/Beego#79]
![image](https://user-images.githubusercontent.com/19927564/44337887-80497d80-a47c-11e8-9775-9c7eb3d7bf31.png)
![image](https://user-images.githubusercontent.com/19927564/44337905-863f5e80-a47c-11e8-8f80-2e9638204785.png)
![image](https://user-images.githubusercontent.com/19927564/44337914-89d2e580-a47c-11e8-9bee-8a77cc0b26fe.png)

**Comment by amirping** [comment]
- [ ] Create the Calendar component  : 80%
